version: '3'

services:
   db:
      build: "./db"
      ports:
         - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: kfrl
        MYSQL_USER: root
        MYSQL_PASSWORD: kfrl
        MYSQL_DATABASE: ocrdev
   web:
      build: "./Urduocr"
      ports:
         - "8000:8000"
      links:
         - db
